# config/sidekiq.yml

:schedule:
  delete_posts:
#     cron: '0 * * * * *'   # Runs once per minute
class: DeletePosts
     every: '24h' # configuring sidekiq scheduler to run every 24 hours and call delete_posts


     :dynamic: true